package com.kltyton.mob_battle.network;

import com.kltyton.mob_battle.network.packet.*;
import net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry;

public class ModPackets {
    public static void init() {
        PayloadTypeRegistry.serverboundPlay().register(
                HighbirdAttackPayload.ID,
                HighbirdAttackPayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                SkillPayload.ID,
                SkillPayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                PlayerSkillPayload.ID,
                PlayerSkillPayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                LeftClickPacket.ID,
                LeftClickPacket.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                HulkbusterEntityPayload.ID,
                HulkbusterEntityPayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                PiglinGeneralBonePayload.ID,
                PiglinGeneralBonePayload.CODEC
        );
        PayloadTypeRegistry.clientboundPlay().register(
                SoundPayload.ID,
                SoundPayload.CODEC
        );
        PayloadTypeRegistry.clientboundPlay().register(
                PlayerSkillUtilPayload.ID,
                PlayerSkillUtilPayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                EnchantmentPayload.ID,
                EnchantmentPayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                SummonDronePayload.ID,
                SummonDronePayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                ItemGroupPayload.ID,
                ItemGroupPayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                MasterScepterPayload.ID,
                MasterScepterPayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                ShieldSpawnPayload.ID,
                ShieldSpawnPayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                ZiJinPayload.ID,
                ZiJinPayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                CompressArmorSkillPayload.ID,
                CompressArmorSkillPayload.CODEC
        );
        PayloadTypeRegistry.serverboundPlay().register(
                PiglinCannonModePayload.ID,
                PiglinCannonModePayload.CODEC
        );
        PayloadTypeRegistry.clientboundPlay().register(
                ItemGroupPayload.ID,
                ItemGroupPayload.CODEC
        );
        PayloadTypeRegistry.clientboundPlay().register(
                ILeadUpdatePayload.ID,
                ILeadUpdatePayload.CODEC
        );
        PayloadTypeRegistry.clientboundPlay().register(
                PermissionPayload.ID,
                PermissionPayload.CODEC
        );
        PayloadTypeRegistry.clientboundPlay().register(
                CustomBossBarPayload.ID,
                CustomBossBarPayload.CODEC
        );
        // 注册服务器向客户端发送的玩家动画同步包。
        PayloadTypeRegistry.clientboundPlay().register(
                PlayerAnimationPayload.ID,
                PlayerAnimationPayload.CODEC
        );
    }
}
